[package]
name = "lua-bytecode"
readme = "README.org"
description = "A lua bytecode parser/encoder for lua5.1 and luau"
repository = "https://github.com/lua-tools/lua-bytecode"

version = "0.3.1"
edition = "2024"
license = "GPL-3.0-only"

[features]
lua51 = []
luau = []

[dependencies]
